# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Will Baird
tagline:          'Blog'
description:      'Rails/Angular/Node software writer'

author:
  name:           'Will Baird'
  url:            https://twitter.com/williamtbaird

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/williamtbaird