# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            WilliamtBaird
tagline:          'Blog'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> 

author:
  name:           'William Baird'
  url:            https://twitter.com/williamtbaird

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/williamtbaird